version: "3.9"

services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guyana
    volumes:
      - ./volumes/sonarr/config:/config
      - ./volumes/media/tv:/media/tv            
      - ./volumes/downloads:/downloads         
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guyana
    volumes:
      - ./volumes/radarr/config:/config
      - ./volumes/media/movies:/media/movies    
      - ./volumes/downloads:/downloads          
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - prowlarr
      - transmission
  
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guyana
    volumes:
      - ./volumes/prowlarr/config:/config
    ports:
      - 9696:9696

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guyana
    volumes:
      - ./volumes/transmission/config:/config
      - ./volumes/downloads:/downloads         
      - ./volumes/transmission/watch:/watch
    ports:
      - 9091:9091

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin_test
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Guyana
    volumes:
      - ./volumes/jellyfin/config:/config
      - ./volumes/jellyfin/cache:/cache
      - ./volumes/media:/media                  
    ports:
      - 8096:8096
      - 8920:8920
    restart: unless-stopped
